[workspace]
authors = ["jgsimard <jeangab23@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge", "https://repo.prefix.dev/modular-community"]
name = "learn_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
aoc25 = "python -c \"import os, sys; [sys.exit(1) for i in range(1, 13) if os.system(f'mojo aoc/2025/d{i}/d{i}.mojo') != 0]\""


[dependencies]
mojo = ">=1.0.0b1.dev2026042505,<2"
max = ">=26.3.0.dev2026042505,<27"
python = ">=3.13.13,<3.14"
numpy = ">=2.4.3,<3"
polars = ">=1.40.0,<2"
tqdm = ">=4.67.3,<5"
pillow = ">=12.2.0,<13"
pygame = ">=2.6.1,<3"
