[workspace]
authors = ["jgsimard <jeangab23@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "learn_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
numpy = ">=2.3.3,<3"
polars = ">=1.34.0,<2"
tqdm = ">=4.67.1,<5"
mojo = ">=0.25.7.0.dev2025100705,<0.26"
